### ISSUE TITLE
hi, just a question :D

### ISSUE THREAD

**Issue by P1R4T3development** [FAXES/LeaveEngineRunning#2]
Hi and thank for this small script!
I've a small question, do you have an idea for a script for dont automatically start engine when you enter in, and dont stop it when you're exiting?
I'm trying that: 

               if LeaveRunning then
			local playerPed = PlayerPedId()
			local vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
			local enginerunning = GetIsVehicleEngineRunning(vehicle)
			if IsPedInAnyVehicle(playerPed, false) and IsControlPressed(2, 75) and not IsEntityDead(playerPed) then
				SetVehicleEngineOn(vehicle, true, true, false)
				TaskLeaveVehicle(playerPed, vehicle, 0)
			end
		end

When i exit of the car the engine not stop (that's good!) but if i kill the engine by my vehicle control script and i exit, the engine start up again :/
Thank's a lot if you've a small idea, and i wish you a nice day :)

**Comment by FAXES** [comment]
That's an issue that can't really be resolved seeming the vehicle control script doesn't register the vehicle engine as damaged most likely. If the game has registered the engine as damaged in-game it wouldn't be allowed to start via this resource.
