### ISSUE TITLE
When vehicle is exited have the high beams stay on 

### ISSUE THREAD

**Issue by MtagGaming** [FAXES/LeaveEngineRunning#3]
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(1)
		local veh = GetVehiclePedIsIn(PlayerPedId(), false)
		if ( IsPedInAnyVehicle(PlayerPedId(), true) ) and ( GetPedInVehicleSeat(veh, false), -1) == PlayerPedId() ) then
			SetVehicleFullbeam(veh, true)
		end
	end
end)

**Comment by FAXES** [comment]
Added
